name: Build
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build
        run: |
          cd app
          npm install --force
          npm run react-build

      - name: Dist
        run: |
          cd app
          npm run dist


      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: app/dist

